### ISSUE TITLE
Can not compile alfresco-collabora-office

### ISSUE THREAD

**Issue by hmirheydari** [CollaboraOnline/alfresco-collabora-online#4]
Just I ran `mvn install` it progressed about one hour and finally stuck to following line:

`Downloading from alfresco-plugin-public: https://artifacts.alfresco.com/nexus/content/groups/public/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
`

I tested the download url in firefox and I got:

```
404 - Path /org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar not found in group repository "Public Releases Repositories (GA)" [id=public].

Path /org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar not found in group repository "Public Releases Repositories (GA)" [id=public].

```

**Comment by jeremie-lesage** [comment]
Hi, 

Sorry for delay, we are not receiving notifications from github :thinking: 

This dependency is on maven central not on the alfresco nexus. I think you have a problem with your maven configuration in '~/.m2/settings.xml` ?

Regards
Jeremie
