### ISSUE TITLE
Preview not updated after edit

### ISSUE THREAD

**Issue by nothing-fr** [CollaboraOnline/alfresco-collabora-online#5]
Hi,

When using your extension, editing a document works but on save / close, the preview is not updated in Alfresco.

- Alfresco Share : v11.77
- Alfresco Community : v7.1.0
- COOLWSD : 21.11.0.6
- Collabora Office : 21.06.10.1
- Alfresco-collabora-online : 0.5.1

Is this a configuration problem ?

**Comment by jeremie-lesage** [comment]
Hi Fred,

Sorry for delay, we are not receiving notifications from github :thinking: 

We have reproduce this bug on our platform, @cindyPiassale is looking for a solution.

regards
Jeremie

**Comment by cindyPiassale** [comment]
Hi Fred,

we have reproduce this bug on our platform Alfresco 7.2.
But this bug is not present on our platform Alfresco 6.2.

We are investigating why the alfresco update brought this bug.

Best regards,
Cindy

**Comment by AlgoJerViA** [comment]
Did you ever follow up on this?

**Comment by jeremie-lesage** [comment]
No, we haven’t found a solution yet. I don’t think it’s a problem with our extension because the problem is not present on Pristy. 

It seems that Alfresco Share doesn’t trigger correctly if there is a new thumbnail. 

We haven’t tried with Alfresco 7.4 yet

**Comment by aborroy** [comment]
It may depend on Alfresco configuration. Alternatively, when updating/unlocking the document in `alfresco-collabora-online` code, a rendition for `preview` and `pdf` can be requested.

**Comment by jeremie-lesage** [comment]
In the latest version, we request a rendering for each update (except for automatic backups).

We have also rewritten the locking mechanism, so our specific Aspect is now obsolete.

I can’t retry the current bug again, as we now have a problem with Alfresco Share. @cindyPiassale is working on this bug. @cindyPiassale is working on this.
